
'use server';

/**
 * @fileOverview A Genkit flow for verifying a Google reCAPTCHA Enterprise token.
 * This flow takes a token and an expected action, and assesses it using the
 * reCAPTCHA Enterprise API to determine if the user interaction is legitimate.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import {
  RecaptchaEnterpriseServiceClient
} from '@google-cloud/recaptcha-enterprise';

// Define Zod schema for the input
const VerifyRecaptchaInputSchema = z.object({
  token: z.string().describe('The reCAPTCHA token generated by the client.'),
  expectedAction: z.string().describe('The action name you expect the token to be associated with (e.g., "LOGIN", "SIGNUP").'),
});

// Define Zod schema for the output
const VerifyRecaptchaOutputSchema = z.object({
  isVerified: z.boolean().describe('True if the token is valid and the score is above the threshold, false otherwise.'),
  score: z.number().describe('The risk score from 0.0 to 1.0. Lower scores indicate higher risk.'),
  reasons: z.array(z.string()).describe('Reasons for the assessment.'),
});

export type VerifyRecaptchaInput = z.infer<typeof VerifyRecaptchaInputSchema>;
export type VerifyRecaptchaOutput = z.infer<typeof VerifyRecaptchaOutputSchema>;

/**
 * Verifies a reCAPTCHA token with Google's reCAPTCHA Enterprise service.
 * @param input An object containing the token and expected action.
 * @returns A promise that resolves to the verification result.
 */
export async function verifyRecaptcha(input: VerifyRecaptchaInput): Promise<VerifyRecaptchaOutput> {
  return await verifyRecaptchaFlow(input);
}


// Define the main Genkit flow
const verifyRecaptchaFlow = ai.defineFlow(
  {
    name: 'verifyRecaptchaFlow',
    inputSchema: VerifyRecaptchaInputSchema,
    outputSchema: VerifyRecaptchaOutputSchema,
  },
  async ({ token, expectedAction }) => {
    
    // IMPORTANT: Make sure the following environment variables are set:
    // - GOOGLE_CLOUD_PROJECT: Your Google Cloud project ID (e.g., "studio-4385357604-24c83")
    // - RECAPTCHA_ENTERPRISE_API_KEY: An API key with reCAPTCHA Enterprise permissions
    // - NEXT_PUBLIC_RECAPTCHA_SITE_KEY: The site key used on the client-side
    
    const projectID = process.env.GOOGLE_CLOUD_PROJECT || "studio-4385357604-24c83";
    const apiKey = process.env.RECAPTCHA_ENTERPRISE_API_KEY;
    const siteKey = "6LcimiAsAAAAAEYqnXn6r1SCpvlUYftwp9nK0wOS";
    
    if (!projectID || !apiKey || !siteKey) {
        console.error("reCAPTCHA environment variables are not fully configured.");
        return { isVerified: false, score: 0, reasons: ["Server configuration error."] };
    }

    const client = new RecaptchaEnterpriseServiceClient();
    const projectPath = client.projectPath(projectID);

    const request = {
      assessment: {
        event: {
          token: token,
          siteKey: siteKey,
          expectedAction: expectedAction,
        },
      },
      parent: projectPath,
    };

    try {
      const [response] = await client.createAssessment(request);

      if (!response.tokenProperties?.valid) {
        return { isVerified: false, score: 0, reasons: response.tokenProperties?.invalidReasons || [] };
      }

      if (response.tokenProperties.action !== expectedAction) {
        return { isVerified: false, score: response.riskAnalysis?.score || 0, reasons: ["Action mismatch."] };
      }

      // Business logic: check if the score is high enough.
      // For this example, we use a threshold of 0.5.
      const score = response.riskAnalysis?.score ?? 0;
      const isVerified = score >= 0.5;

      return {
        isVerified,
        score,
        reasons: response.riskAnalysis?.reasons || [],
      };

    } catch (error) {
      console.error('reCAPTCHA assessment failed:', error);
      return { isVerified: false, score: 0, reasons: ["Assessment API call failed."] };
    }
  }
);
