import type { Challenge } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const staticChallenges: Challenge[] = [
  // Facile
  {
    id: 'namur-facile-1',
    creatorId: 'admin-studin',
    title: "Le Beffroi de Namur",
    description: "Prenez une photo du Beffroi de Namur, classé au patrimoine de l'UNESCO. Un incontournable de la ville !",
    category: 'Exploration',
    difficulty: 'facile',
    points: 10,
    imageUrl: 'https://images.unsplash.com/photo-1620766385807-617a943a8b20?q=80&w=2070&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.4673,
    longitude: 4.8675,
    createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-facile-1',
    creatorId: 'admin-studin',
    title: "L'Atomium Iconique",
    description: "Prenez un selfie avec l'Atomium en arrière-plan. Assurez-vous que l'ensemble du monument soit visible !",
    category: 'Exploration',
    difficulty: 'facile',
    points: 10,
    imageUrl: 'https://images.unsplash.com/photo-1599709835737-27b6b15a7e6b?q=80&w=1974&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.8949,
    longitude: 4.3415,
    createdAt: { seconds: 1672531201, nanoseconds: 0 } as any,
  },
  {
    id: 'namur-facile-2',
    creatorId: 'admin-studin',
    title: "Poubelle Héroïque",
    description: "Trouvez une poubelle publique qui déborde et ramassez au moins 3 déchets autour. Postez une photo de votre bonne action (poubelle + déchets ramassés).",
    category: 'Social',
    difficulty: 'facile',
    points: 15,
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?q=80&w=1974&auto=format&fit=crop',
    location: 'Namur',
    createdAt: { seconds: 1672531202, nanoseconds: 0 } as any,
  },
  // Moyen
  {
    id: 'namur-moyen-1',
    creatorId: 'admin-studin',
    title: "L'Ascension de la Citadelle",
    description: "Montez au sommet de la Citadelle de Namur (à pied ou à vélo !) et prenez une photo panoramique prouvant votre exploit.",
    category: 'Exploration',
    difficulty: 'moyen',
    points: 25,
    imageUrl: 'https://images.unsplash.com/photo-1620202271383-34445b73650c?q=80&w=2070&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.459,
    longitude: 4.863,
    createdAt: { seconds: 1672531203, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-moyen-1',
    creatorId: 'admin-studin',
    title: "Jogging au Parc Royal",
    description: "Faites un tour de jogging (ou de marche rapide) dans le Parc de Bruxelles. Postez un selfie post-effort avec une vue reconnaissable du parc.",
    category: 'Social',
    difficulty: 'moyen',
    points: 20,
    imageUrl: 'https://images.unsplash.com/photo-1593492323395-7b5611c69a08?q=80&w=1974&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.845,
    longitude: 4.364,
    createdAt: { seconds: 1672531204, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-moyen-2',
    creatorId: 'admin-studin',
    title: "Le Secret du Mont des Arts",
    description: "Trouvez le jardin caché du Mont des Arts et prenez une photo artistique de la vue sur le centre-ville.",
    category: 'Exploration',
    difficulty: 'moyen',
    points: 25,
    imageUrl: 'https://images.unsplash.com/photo-1569097480572-125c1cf682f4?q=80&w=1964&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.844,
    longitude: 4.357,
    createdAt: { seconds: 1672531205, nanoseconds: 0 } as any,
  },
  // Difficile
  {
    id: 'namur-difficile-1',
    creatorId: 'admin-studin',
    title: "Fresque des Wallons Créative",
    description: "Trouvez la 'Fresque des Wallons' à Namur et recréez la pose d'un des personnages de manière originale et reconnaissable.",
    category: 'Créatif',
    difficulty: 'difficile',
    points: 50,
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=2070&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.464,
    longitude: 4.866,
    createdAt: { seconds: 1672531206, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-difficile-1',
    creatorId: 'admin-studin',
    title: "Exploration Urbaine : La Tour Financière",
    description: "Trouvez un point de vue original (et accessible au public !) pour photographier la Tour des Finances avec un élément urbain inattendu au premier plan.",
    category: 'Créatif',
    difficulty: 'difficile',
    points: 40,
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2070&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.85,
    longitude: 4.35,
    createdAt: { seconds: 1672531207, nanoseconds: 0 } as any,
  },
];
