import type { Challenge } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const staticChallenges: Challenge[] = [
  {
    id: '1',
    creatorId: 'admin-user',
    title: "Le Lion de Waterloo",
    description: "Prenez un selfie au pied de la Butte du Lion. Un classique ! Assurez-vous que le monument soit bien visible derrière vous.",
    category: 'Exploration',
    difficulty: 'facile',
    points: 10,
    imageUrl: PlaceHolderImages.find(p => p.id === 'challenge-1')?.imageUrl || '',
    location: 'Waterloo',
    latitude: 50.678,
    longitude: 4.405,
    createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: '2',
    creatorId: 'admin-user',
    title: "Street Art à Bruxelles",
    description: "Trouvez et photographiez la fresque de Tintin et du Capitaine Haddock dans le centre-ville de Bruxelles.",
    category: 'Créatif',
    difficulty: 'moyen',
    points: 25,
    imageUrl: PlaceHolderImages.find(p => p.id === 'challenge-2')?.imageUrl || '',
    location: 'Bruxelles',
    latitude: 50.846,
    longitude: 4.352,
     createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: '3',
    creatorId: 'admin-user',
    title: "Vue panoramique de Namur",
    description: "Montez au sommet de la Citadelle et capturez la vue sur la Meuse et la Sambre au coucher du soleil.",
    category: 'Exploration',
    difficulty: 'moyen',
    points: 20,
    imageUrl: PlaceHolderImages.find(p => p.id === 'challenge-3')?.imageUrl || '',
    location: 'Namur',
    latitude: 50.459,
    longitude: 4.863,
     createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: '4',
    creatorId: 'admin-user',
    title: "Participer à une Cantus",
    description: "Immortalisez l'ambiance d'une cantus étudiante. Votre photo doit montrer votre codex ou votre verre.",
    category: 'Social',
    difficulty: 'facile',
    points: 15,
    imageUrl: PlaceHolderImages.find(p => p.id === 'challenge-4')?.imageUrl || '',
    createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: '5',
    creatorId: 'partner-account-id',
    title: "L'énigme du Manneken-Pis",
    description: "Trouvez l'indice de la semaine sur le costume du Manneken-Pis et décryptez l'énigme pour gagner des points.",
    category: 'Créatif',
    difficulty: 'difficile',
    points: 50,
    imageUrl: PlaceHolderImages.find(p => p.id === 'challenge-5')?.imageUrl || '',
    location: 'Bruxelles',
    createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
];
