import type { Challenge } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const staticChallenges: Challenge[] = [
  // --- FACILE ---
  {
    id: 'namur-facile-1',
    creatorId: 'admin-studin',
    title: "Selfie au Beffroi de Namur",
    description: "Prenez un selfie avec le Beffroi de Namur, classé au patrimoine de l'UNESCO. Un incontournable de la ville !",
    category: 'Exploration',
    difficulty: 'facile',
    points: 10,
    imageUrl: 'https://images.unsplash.com/photo-1632194634234-a8a25c197d62?q=80&w=1964&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.4673,
    longitude: 4.8675,
    createdAt: { seconds: 1672531200, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-facile-1',
    creatorId: 'admin-studin',
    title: "L'Atomium Iconique",
    description: "Prenez une photo créative avec l'Atomium en arrière-plan. Surprenez-nous !",
    category: 'Exploration',
    difficulty: 'facile',
    points: 10,
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?q=80&w=1964&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.8949,
    longitude: 4.3415,
    createdAt: { seconds: 1672531201, nanoseconds: 0 } as any,
  },
  {
    id: 'namur-facile-2',
    creatorId: 'admin-studin',
    title: "Héros de la Propreté",
    description: "Trouvez une poubelle publique et ramassez 3 déchets autour. Postez une photo de votre butin avant de le jeter. Un petit geste pour une grande cause.",
    category: 'Social',
    difficulty: 'facile',
    points: 15,
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?q=80&w=1974&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.466,
    longitude: 4.86,
    createdAt: { seconds: 1672531202, nanoseconds: 0 } as any,
  },
  // --- MOYEN ---
  {
    id: 'namur-moyen-1',
    creatorId: 'admin-studin',
    title: "Panorama depuis la Citadelle",
    description: "Montez au sommet de la Citadelle (à pied, c'est mieux !) et prenez une photo panoramique de la vue sur la Meuse et la ville.",
    category: 'Exploration',
    difficulty: 'moyen',
    points: 25,
    imageUrl: 'https://images.unsplash.com/photo-1601046838339-32c02c6114a3?q=80&w=2070&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.459,
    longitude: 4.863,
    createdAt: { seconds: 1672531203, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-moyen-1',
    creatorId: 'admin-studin',
    title: "Pause Sportive au Cinquantenaire",
    description: "Faites une séance de sport (course, yoga, étirements...) sous les arcades du Cinquantenaire et immortalisez le moment.",
    category: 'Social',
    difficulty: 'moyen',
    points: 20,
    imageUrl: 'https://images.unsplash.com/photo-1593492323395-7b5611c69a08?q=80&w=1974&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.842,
    longitude: 4.391,
    createdAt: { seconds: 1672531204, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-moyen-2',
    creatorId: 'admin-studin',
    title: "Le Jardin Caché du Mont des Arts",
    description: "Trouvez le jardin secret du Mont des Arts et prenez une photo artistique de la vue sur l'hôtel de ville.",
    category: 'Exploration',
    difficulty: 'moyen',
    points: 25,
    imageUrl: 'https://images.unsplash.com/photo-1569097480572-125c1cf682f4?q=80&w=1964&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.844,
    longitude: 4.357,
    createdAt: { seconds: 1672531205, nanoseconds: 0 } as any,
  },
  // --- DIFFICILE ---
  {
    id: 'namur-difficile-1',
    creatorId: 'admin-studin',
    title: "La Fresque des Wallons en Scène",
    description: "Trouvez la 'Fresque des Wallons' et recréez de manière originale la pose d'un des personnages. Mettez en scène votre version !",
    category: 'Créatif',
    difficulty: 'difficile',
    points: 50,
    imageUrl: 'https://images.unsplash.com/photo-1518779578993-6bae685069f6?q=80&w=2070&auto=format&fit=crop',
    location: 'Namur',
    latitude: 50.464,
    longitude: 4.866,
    createdAt: { seconds: 1672531206, nanoseconds: 0 } as any,
  },
  {
    id: 'bxl-difficile-1',
    creatorId: 'admin-studin',
    title: "Perspective sur la Tour des Finances",
    description: "Trouvez un angle de vue unique et artistique pour photographier la Tour des Finances, en incluant un élément inattendu au premier plan.",
    category: 'Créatif',
    difficulty: 'difficile',
    points: 40,
    imageUrl: 'https://images.unsplash.com/photo-1608269733436-0c9f53c15812?q=80&w=1964&auto=format&fit=crop',
    location: 'Bruxelles',
    latitude: 50.852,
    longitude: 4.36,
    createdAt: { seconds: 1672531207, nanoseconds: 0 } as any,
  },
];
