// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
// Your project's Firebase configuration.
export const firebaseConfig = {
  "projectId": "studio-4385357604-24c83",
  "appId": "1:1039469624980:web:f6c7426a7c7e931406fe81",
  "storageBucket": "studio-4385357604-24c83.appspot.com",
  "apiKey": "AIzaSyAc8X2IT14tHo80hkg7IzY00jRH4PuB2o4",
  "authDomain": "studio-4385357604-24c83.firebaseapp.com",
  "messagingSenderId": "1039469624980",
  "measurementId": "G-7BY1EKEC8X"
};
